# Generated by Django 6.0 on 2025-12-11 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('template_type', models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('configuration', models.JSONField(default=dict, help_text='Template configuration and settings')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'db_table': 'reports_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('export_type', models.CharField(max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('result_file', models.FileField(blank=True, upload_to='exports/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'db_table': 'reports_export_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('module', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Structured log data')),
                ('traceback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'db_table': 'reports_log_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', '-created_at'], name='reports_log_level_7e2a38_idx'), models.Index(fields=['module', '-created_at'], name='reports_log_module_7e627f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreatStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_threats', models.IntegerField(default=0)),
                ('critical_threats', models.IntegerField(default=0)),
                ('warning_threats', models.IntegerField(default=0)),
                ('info_threats', models.IntegerField(default=0)),
                ('arp_spoofs', models.IntegerField(default=0)),
                ('dns_spoofs', models.IntegerField(default=0)),
                ('rogue_dhcp', models.IntegerField(default=0)),
                ('mac_duplicates', models.IntegerField(default=0)),
                ('blocked_ips', models.IntegerField(default=0)),
                ('alerts_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Threat Statistic',
                'verbose_name_plural': 'Threat Statistics',
                'db_table': 'reports_threat_statistic',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='reports_thr_date_3aa872_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('CUSTOM', 'Custom Report')], default='CUSTOM', max_length=20)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('HTML', 'HTML')], default='PDF', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('file_path', models.FileField(blank=True, upload_to='reports/')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports_report',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['-generated_at'], name='reports_rep_generat_fa1e6b_idx'), models.Index(fields=['report_type', '-generated_at'], name='reports_rep_report__a7c87c_idx')],
            },
        ),
    ]
