# Generated by Django 6.0 on 2025-12-11 00:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('ARP_SPOOF', 'ARP Spoofing'), ('ARP_POISON', 'ARP Poisoning'), ('DNS_SPOOF', 'DNS Spoofing'), ('ROGUE_DHCP', 'Rogue DHCP Server'), ('MAC_DUPLICATE', 'MAC Address Duplication'), ('ARP_SCAN', 'ARP Scan Detected')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('description', models.TextField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detected Threat',
                'verbose_name_plural': 'Detected Threats',
                'db_table': 'detector_detected_threat',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='MACAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_whitelisted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('associated_ips', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MAC Address',
                'verbose_name_plural': 'MAC Addresses',
                'db_table': 'detector_mac_address',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('is_active', models.BooleanField(default=True)),
                ('is_monitoring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network Interface',
                'verbose_name_plural': 'Network Interfaces',
                'db_table': 'detector_network_interface',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
                ('rule_name', models.CharField(blank=True, max_length=255)),
                ('is_permanent', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detector.detectedthreat')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'db_table': 'detector_blocked_ip',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.AddField(
            model_name='detectedthreat',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detector.networkinterface'),
        ),
        migrations.CreateModel(
            name='ARPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('is_legitimate', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('times_changed', models.IntegerField(default=0)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.networkinterface')),
            ],
            options={
                'verbose_name': 'ARP Entry',
                'verbose_name_plural': 'ARP Entries',
                'db_table': 'detector_arp_entry',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='DNSQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('query_type', models.CharField(default='A', max_length=10)),
                ('resolved_ip', models.GenericIPAddressField()),
                ('is_legitimate', models.BooleanField(default=True)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.networkinterface')),
            ],
            options={
                'verbose_name': 'DNS Query',
                'verbose_name_plural': 'DNS Queries',
                'db_table': 'detector_dns_query',
                'ordering': ['-queried_at'],
                'indexes': [models.Index(fields=['domain', '-queried_at'], name='detector_dn_domain_de943a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DHCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField()),
                ('server_mac', models.CharField(max_length=17)),
                ('is_legitimate', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('offer_count', models.IntegerField(default=0)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.networkinterface')),
            ],
            options={
                'verbose_name': 'DHCP Server',
                'verbose_name_plural': 'DHCP Servers',
                'db_table': 'detector_dhcp_server',
                'ordering': ['-last_seen'],
                'unique_together': {('server_ip', 'server_mac', 'interface')},
            },
        ),
        migrations.AddIndex(
            model_name='detectedthreat',
            index=models.Index(fields=['-detected_at'], name='detector_de_detecte_8d8a55_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedthreat',
            index=models.Index(fields=['threat_type', '-detected_at'], name='detector_de_threat__856d62_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedthreat',
            index=models.Index(fields=['severity'], name='detector_de_severit_ff9171_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='arpentry',
            unique_together={('ip_address', 'interface')},
        ),
    ]
